package io.artoo.lance.func;

public final class CallableException extends Exception {
  CallableException(Throwable throwable) {
    super(throwable);
  }
}
